/**
 * Property-based tests for HttpUserProfileClient field mapping.
 *
 * **Property 1: UPS profile pre-population maps all fields**
 * For any valid UpsProfileResponse shape (generated by fast-check),
 * `getProfile` must produce a UpsProfile where every field matches
 * the defined snake_case → camelCase mapping with no fields dropped
 * or defaulted incorrectly.
 *
 * **Validates: Requirements 1.3, 1.7, 14.3**
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import * as fc from "fast-check";
import { HttpClient } from "../http/HttpClient";
import { HttpUserProfileClient } from "./HttpUserProfileClient";

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeResponse(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

/**
 * Arbitrary that generates a valid UpsProfileDto (snake_case wire format).
 * String fields are nullable; boolean fields are nullable.
 */
const upsProfileDtoArb = fc.record({
  user_id: fc.string({ minLength: 1, maxLength: 50 }),
  full_name: fc.oneof(fc.string(), fc.constant(null)),
  date_of_birth: fc.oneof(
    fc
      .date({ min: new Date("1900-01-01"), max: new Date("2025-12-31") })
      .map((d) => d.toISOString().slice(0, 10)),
    fc.constant(null),
  ),
  phone: fc.oneof(fc.string(), fc.constant(null)),
  street: fc.oneof(fc.string(), fc.constant(null)),
  city: fc.oneof(fc.string(), fc.constant(null)),
  state: fc.oneof(fc.string(), fc.constant(null)),
  postal_code: fc.oneof(fc.string(), fc.constant(null)),
  country: fc.oneof(fc.string(), fc.constant(null)),
  bio: fc.oneof(fc.string(), fc.constant(null)),
  display_name: fc.oneof(fc.string(), fc.constant(null)),
  notification_email: fc.oneof(fc.boolean(), fc.constant(null)),
  notification_sms: fc.oneof(fc.boolean(), fc.constant(null)),
  notification_whatsapp: fc.oneof(fc.boolean(), fc.constant(null)),
  language: fc.oneof(
    fc.stringOf(fc.constantFrom("a", "b", "c", "d", "e"), {
      minLength: 2,
      maxLength: 2,
    }),
    fc.constant(null),
  ),
  timezone: fc.oneof(fc.string(), fc.constant(null)),
});

// ── Setup / Teardown ──────────────────────────────────────────────────────────

beforeEach(() => {
  HttpClient._resetInstance();
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ── Property 1 ────────────────────────────────────────────────────────────────

describe("Property 1: UPS profile pre-population maps all fields", () => {
  it("maps every snake_case DTO field to the correct camelCase UpsProfile field", async () => {
    await fc.assert(
      fc.asyncProperty(upsProfileDtoArb, async (dto) => {
        vi.stubGlobal(
          "fetch",
          vi.fn().mockResolvedValue(makeResponse(200, dto)),
        );

        const client = new HttpUserProfileClient();
        const profile = await client.getProfile(dto.user_id);

        // Verify the complete snake_case → camelCase mapping
        expect(profile.userId).toBe(dto.user_id);
        expect(profile.fullName).toBe(dto.full_name);
        expect(profile.dateOfBirth).toBe(dto.date_of_birth);
        expect(profile.phone).toBe(dto.phone);
        expect(profile.street).toBe(dto.street);
        expect(profile.city).toBe(dto.city);
        expect(profile.state).toBe(dto.state);
        expect(profile.postalCode).toBe(dto.postal_code);
        expect(profile.country).toBe(dto.country);
        expect(profile.bio).toBe(dto.bio);
        expect(profile.displayName).toBe(dto.display_name);
        expect(profile.notificationEmail).toBe(dto.notification_email);
        expect(profile.notificationSms).toBe(dto.notification_sms);
        expect(profile.notificationWhatsapp).toBe(dto.notification_whatsapp);
        expect(profile.language).toBe(dto.language);
        expect(profile.timezone).toBe(dto.timezone);

        // Verify no extra fields are introduced
        const profileKeys = Object.keys(profile).sort();
        const expectedKeys = [
          "userId",
          "fullName",
          "dateOfBirth",
          "phone",
          "street",
          "city",
          "state",
          "postalCode",
          "country",
          "bio",
          "displayName",
          "notificationEmail",
          "notificationSms",
          "notificationWhatsapp",
          "language",
          "timezone",
        ].sort();
        expect(profileKeys).toEqual(expectedKeys);
      }),
      { numRuns: 100 },
    );
  });
});
